export const mockContent = { damageItemDetails:
   { labourDetails:
      { craft: { craftID: null, description: '', skillLevelID: null },
        description: '',
        labourUnitID: null,
        workValue: null,
        labourRate: null,
        poweredByID: 1,
        labourDeviationUsed: null,
        labourRateAdjusted: null },
     flatRateDetails: { description: '', price: 0 },
     toolDetails: { description: '', quantity: 1, unitID: null, price: 0 },
     contentDetail:
      { attachments: [],
        condition: '',
        model: '',
        shouldBeRepaired: false,
        purchaseDate: '2017-08-03T11:28:44+01:00',
        repairCost: 0 },
     calculationStep: [],
     invoiceDetails: null,
     depreciationDetails: { note: '', age: 0, correctionFactor: 0, lifetime: 0 },
     materialDetails: { description: '', quantity: 1, unitID: null, price: 0 },
     unitPriceDetails: { description: '', unitPrice: 0 } },
  serviceBundleGroupID: null,
  orderValue: null,
  alreadyRepaired: null,
  unit: null,
  total:
   { totalTypeID: null,
     tax: { taxTypeID: 2, tax: 19 },
     depreciation: { depreciationTypeID: null, depreciation: 0 },
     totalNewValue: 0,
     grandTotal: 0,
     grandTotalIncludingTax: 0 },
  qualityLevel: { description: null, ID: 0 },
  pricingServiceID: null,
  quantity: 1,
  locationID: null,
  note: '',
  id: '1e9f49a1-5943-b235-a758-35c6d668b899',
  damageItemType: { description: 'CONTENT', ID: 6 },
  description: 'fooo',
  unitID: null };
